name: 'Unit Tests'

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/tests.yml'
      - '**.go'
      - 'go.sum'
      - 'go.mod'
  pull_request:
    branches:
      - 'main'

jobs:
  vet-and-test:
    runs-on:
      - 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          check-latest: true
          cache: true

      - shell: bash -e {0}
        # language=sh
        run: go test ./...'